services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./database:/qdrant/storage

  app:
    build: .
    expose:
      - "8501"
    environment:
      - QDRANT_URL=http://qdrant:6333
    depends_on:
      - qdrant

  caddy:
    image: caddy:2
    ports:
      - "80:80"
    command: caddy reverse-proxy --from :80 --to app:8501
    depends_on:
      - app
